name: Validate

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - run: npm ci --prefer-offline --no-audit

      - run: npm run check

      - run: npm run type:check
