name: Validate

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: npm ci --prefer-offline --no-audit

      - run: npm run lint:check

      - run: npm run format:check

      - run: npm run type:check
